### ISSUE TITLE
Not seeing minor version bumped when feat: is used

### ISSUE THREAD

**Issue by agronick** [oflynned/android-version-bump#122]
I have been prefixing my commits with `fix:` and `feat:`. I am only seeing the minor version get bumped. At first I thought it was only looking at the last commits instead of all the commits since the last bump but that doesn't seem to be the case. You can see the repo here:

https://github.com/agronick/aa-torque

**Comment by agronick** [comment]
It only has 3 enviorment variables but it appears to be looking for a lot more. Do I have to do something for them to show up?

```
Run oflynned/android-version-bump@master
  with:
    skip_ci: true
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/19.0.[2](https://github.com/agronick/Flattery/actions/runs/7227563206/job/19695508122#step:8:2)-7/x64
    JAVA_HOME_19_X64: /opt/hostedtoolcache/Java_Zulu_jdk/19.0.2-7/x64
    GITHUB_TOKEN: ***
/usr/bin/docker run --name ebfd04550[3](https://github.com/agronick/Flattery/actions/runs/7227563206/job/19695508122#step:8:3)ce220ac[4](https://github.com/agronick/Flattery/actions/runs/7227563206/job/19695508122#step:8:4)e8[5](https://github.com/agronick/Flattery/actions/runs/7227563206/job/19695508122#step:8:5)9b12817ce20[6](https://github.com/agronick/Flattery/actions/runs/7227563206/job/19695508122#step:8:6)8f3f_8d1223 --label [7](https://github.com/agronick/Flattery/actions/runs/7227563206/job/19695508122#step:8:7)ebfd0 --workdir /github/workspace --rm -e "JAVA_HOME" -e "JAVA_HOME_19_X64" -e "GITHUB_TOKEN" -e "INPUT_TAG_PREFIX" -e "INPUT_SKIP_CI" -e "INPUT_COMMIT_MESSAGE" -e "INPUT_BUILD_NUMBER" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/Flattery/Flattery":"/github/workspace" 7ebfd0:45503ce220ac4e[8](https://github.com/agronick/Flattery/actions/runs/7227563206/job/19695508122#step:8:9)59b12817ce2068f3f
```
